#!/bin/bash
# Claude Code Instant Setup - One-Liner Command Generator

echo "🚀 Claude Code Instant Setup Command Generator"
echo "=============================================="
echo ""
echo "📋 Copy and paste this ONE-LINER command to instantly setup Claude Code ecosystem on ANY system:"
echo ""
echo "🔥 ONE-LINER COMMAND:"
echo "----------------------------------------------------------------------------------------------------"
echo "curl -fsSL https://raw.githubusercontent.com/ruvnet/claude-code-setup/main/setup.sh | bash"
echo "----------------------------------------------------------------------------------------------------"
echo ""
echo "✨ This command will:"
echo "  ✅ Install Claude Code"
echo "  ✅ Setup 13 MCP servers"
echo "  ✅ Configure 54+ agents"
echo "  ✅ Create complete documentation"
echo "  ✅ Setup SPARC methodology"
echo "  ✅ Configure workflow automation"
echo "  ✅ Create quick start scripts"
echo "  ✅ Enable 2.8-4.4x speed improvement"
echo ""
echo "⚡ SETUP TIME: 5-10 minutes"
echo ""
echo "🎯 PERFECT FOR:"
echo "  • New development environments"
echo "  • Cloud instances (AWS, GCP, Azure)"
echo "  • Docker containers"
echo "  • Team member onboarding"
echo "  • CI/CD pipelines"
echo ""
echo "🔧 REQUIREMENTS:"
echo "  • Ubuntu/Debian Linux"
echo "  • Internet connection"
echo "  • Non-root user account"
echo ""
echo "📚 WHAT YOU GET:"
echo "  • Complete Claude Code ecosystem"
echo "  • 84.8% SWE-Bench solve rate"
echo "  • 32.3% token reduction"
echo "  • 27+ neural models"
echo "  • Enterprise-grade development tools"
echo ""
echo "🚀 ALTERNATIVE ONE-LINERS:"
echo ""
echo "# Option 2: Using wget"
echo "wget -qO- https://raw.githubusercontent.com/ruvnet/claude-code-setup/main/setup.sh | bash"
echo ""
echo "# Option 3: Using git clone and run"
echo "git clone https://github.com/ruvnet/claude-code-setup.git && cd claude-code-setup && chmod +x setup.sh && ./setup.sh"
echo ""
echo "# Option 4: Direct execution (if you have the script locally)"
echo "bash /path/to/claude-one-liner-setup.sh"
echo ""
echo "🎉 READY TO DEPLOY!"
echo ""
echo "Just copy the one-liner command above and run it on any compatible system."
echo "Your complete Claude Code ecosystem will be ready in minutes! 🎯"