#!/bin/bash
# Claude AI Agents Quick Reference

echo "🤖 Claude AI Agents Quick Reference"
echo "===================================="
echo ""

echo "🏗️  Architecture & Design:"
echo "  backend-architect     - RESTful API design, microservices"
echo "  frontend-developer    - React components, responsive layouts"
echo "  cloud-architect      - AWS/Azure/GCP infrastructure design"
echo "  kubernetes-architect  - Cloud-native infrastructure"
echo "  graphql-architect     - GraphQL schemas, federation"
echo "  ui-ux-designer        - Interface design, wireframes"
echo ""

echo "💻 Programming Languages:"
echo "  javascript-pro        - Modern JavaScript, ES6+, Node.js"
echo "  typescript-pro        - Advanced TypeScript, type systems"
echo "  python-pro           - Python development, optimization"
echo "  java-pro             - Modern Java, streams, concurrency"
echo "  rust-pro             - Memory-safe systems programming"
echo "  golang-pro           - Concurrent programming, goroutines"
echo "  csharp-pro           - C# development, .NET frameworks"
echo "  php-pro              - Modern PHP, frameworks"
echo "  ruby-pro             - Ruby, Rails patterns, gems"
echo ""

echo "🔒 Quality & Security:"
echo "  code-reviewer         - Security-focused code review"
echo "  security-auditor      - Vulnerability assessment, OWASP"
echo "  test-automator        - Unit, integration, E2E tests"
echo "  performance-engineer  - Application profiling, optimization"
echo "  debugger             - Error resolution, root cause analysis"
echo "  error-detective       - Log analysis, pattern recognition"
echo ""

echo "🤖 Data & AI:"
echo "  ai-engineer          - LLM applications, RAG systems"
echo "  ml-engineer          - ML pipelines, model serving"
echo "  data-scientist       - Data analysis, SQL queries"
echo "  data-engineer        - ETL pipelines, data warehouses"
echo "  prompt-engineer      - LLM prompt optimization"
echo ""

echo "📱 Mobile & UI:"
echo "  mobile-developer     - React Native, Flutter apps"
echo "  ios-developer        - Native iOS, Swift/SwiftUI"
echo "  flutter-expert       - Advanced Flutter development"
echo "  ui-visual-validator   - Visual regression testing"
echo ""

echo "🏢 Business & Operations:"
echo "  business-analyst      - Metrics analysis, KPI tracking"
echo "  content-marketer      - Blog posts, social media"
echo "  customer-support      - Support tickets, FAQ responses"
echo "  legal-advisor         - Privacy policies, terms of service"
echo "  hr-pro               - HR operations, policies"
echo ""

echo "🔧 DevOps & Infrastructure:"
echo "  devops-troubleshooter - Production debugging, logs"
echo "  deployment-engineer  - CI/CD pipelines, containers"
echo "  terraform-specialist - Infrastructure as Code"
echo "  database-admin       - Database operations, backup"
echo "  network-engineer      - Network debugging, load balancing"
echo ""

echo "📚 Documentation & Content:"
echo "  docs-architect        - Technical documentation"
echo "  api-documenter        - OpenAPI/Swagger specs"
echo "  tutorial-engineer     - Step-by-step tutorials"
echo "  mermaid-expert        - Diagram creation"
echo ""

echo "🎯 Usage Examples:"
echo "  'Use code-reviewer to analyze the recent changes'"
echo "  'Have security-auditor scan for vulnerabilities'"
echo "  'Get performance-engineer to optimize this bottleneck'"
echo "  'Implement user authentication' (automatic delegation)"
echo ""

echo "📖 For complete documentation:"
echo "  cat ~/CLAUDE_DEV_TOOLS_SETUP.md"